services:
  flask-app:
    build: .
    container_name: flask_devops_project
    ports:
      - "5000:5000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus_monitor
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    networks:
      - monitor-net

networks:
  monitor-net: